### ISSUE TITLE
Prohibited Sign

### ISSUE THREAD

**Issue by telepati** [chris1111/MACOSXInstaller#1]
I used your MACOSXInstaller tool and I am getting prohibited sign. I follow every step on the video but still getting sign. What can you suggest? I attached -v screen.

**This is my spec;**
ASUS Z170-A 
INTEL Core i7-6700K LGA 1151
Intel HD 530 
Samsung EVO 250 GB SSD (_**Sierra Installed**_)
Samsung EVO 960 250GB M.2 NVME **(_I created Install media with your tool inside of this Drive_)**

![versobe](https://user-images.githubusercontent.com/3812286/30502648-d87ef92a-9a6f-11e7-942f-57f0c2955b35.jpg)

**Comment by chris1111** [comment]
Which revision of Clover do you use ?
Which kext you with in Clover /10.13 ?
What is your config material, I do not know your material ?

The program will change soon because now Clover can be used on an APFS Volumes
stay tune for the Update and new video

**Comment by chris1111** [comment]
I know you have made a working High Sierra installation, so try to using the same  working config.plist as well as kexts use

**Comment by telepati** [comment]
Ok then I will wait new program.
